// <auto-generated />
using Demo.Domain.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo.Domain.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class AdventureWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo.Domain.Child", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ParentID");

                    b.HasKey("Id");

                    b.HasIndex("ParentID");

                    b.ToTable("Child","Relations");
                });

            modelBuilder.Entity("Demo.Domain.Models.AutoGeneratedKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("AutoGeneratedKey","Keys");
                });

            modelBuilder.Entity("Demo.Domain.Models.NoAutoGeneratedKey", b =>
                {
                    b.Property<int>("Id");

                    b.HasKey("Id");

                    b.ToTable("NoAutoGeneratedKey","Keys");
                });

            modelBuilder.Entity("Demo.Domain.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Parent","Relations");
                });

            modelBuilder.Entity("Demo.Domain.Child", b =>
                {
                    b.HasOne("Demo.Domain.Parent", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentID")
                        .HasConstraintName("FK_B_A")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
