using System;
using System.Collections.Generic;
using System.Text;

namespace Demo.Domain.Models
{
    public class AutoGeneratedKey
    {
        // Mapt op een 'Identity' column: de database kent een nummer toe.
        public int Id { get; set; }
    }
}
