using Microsoft.EntityFrameworkCore;
using Demo.Domain.Models;
using System;
using System.Collections.Generic;
using System.Text;
using System.Linq;

namespace Demo.Domain
{
    public class KeyManager
    {
        /// <summary>
        /// </summary>
        /// <returns>
        /// Geeft de max value terug van de 'Id' column in NoAutoGeneratedKey.
        /// </returns>
        public int GetMaxKey()
        {
            using (var ctx = new DemoDbContext())
            {
                if (ctx.NoAutoGeneratedKeySet.Count() == 0)
                {
                    return 1;
                }
                else
                {
                    return ctx.NoAutoGeneratedKeySet.Max(n => n.Id);
                }                
            }
        }

        public void AddAutoGeneratedKey(AutoGeneratedKey entity)
        {
            using (var ctx = new DemoDbContext())
            {
                ctx.AutoGeneratedKeySet.Add(entity);
                ctx.SaveChanges();
                // Nu heeft de database zelf een nummer toegekend.
            }
        }

        public void AddNoAutoGeneratedKey(NoAutoGeneratedKey entity)
        {
            using (var ctx = new DemoDbContext())
            {
                ctx.NoAutoGeneratedKeySet.Add(entity);
                ctx.SaveChanges();
            }
        }
    }
}
